// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cache.proto

/*
Package cache is a generated protocol buffer package.

It is generated from these files:
	cache.proto

It has these top-level messages:
	GrpcVMConfig
	GrpcVM
*/
package cache

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GrpcVMConfig struct {
	Data        []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	AgentConfig []byte `protobuf:"bytes,2,opt,name=AgentConfig,proto3" json:"AgentConfig,omitempty"`
}

func (m *GrpcVMConfig) Reset()                    { *m = GrpcVMConfig{} }
func (m *GrpcVMConfig) String() string            { return proto.CompactTextString(m) }
func (*GrpcVMConfig) ProtoMessage()               {}
func (*GrpcVMConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GrpcVMConfig) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GrpcVMConfig) GetAgentConfig() []byte {
	if m != nil {
		return m.AgentConfig
	}
	return nil
}

type GrpcVM struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Hypervisor []byte `protobuf:"bytes,2,opt,name=hypervisor,proto3" json:"hypervisor,omitempty"`
	ProxyPid   int64  `protobuf:"varint,3,opt,name=proxyPid" json:"proxyPid,omitempty"`
	ProxyURL   string `protobuf:"bytes,4,opt,name=proxyURL" json:"proxyURL,omitempty"`
	Cpu        uint32 `protobuf:"varint,5,opt,name=cpu" json:"cpu,omitempty"`
	Memory     uint32 `protobuf:"varint,6,opt,name=memory" json:"memory,omitempty"`
	CpuDelta   uint32 `protobuf:"varint,7,opt,name=cpuDelta" json:"cpuDelta,omitempty"`
}

func (m *GrpcVM) Reset()                    { *m = GrpcVM{} }
func (m *GrpcVM) String() string            { return proto.CompactTextString(m) }
func (*GrpcVM) ProtoMessage()               {}
func (*GrpcVM) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GrpcVM) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GrpcVM) GetHypervisor() []byte {
	if m != nil {
		return m.Hypervisor
	}
	return nil
}

func (m *GrpcVM) GetProxyPid() int64 {
	if m != nil {
		return m.ProxyPid
	}
	return 0
}

func (m *GrpcVM) GetProxyURL() string {
	if m != nil {
		return m.ProxyURL
	}
	return ""
}

func (m *GrpcVM) GetCpu() uint32 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *GrpcVM) GetMemory() uint32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *GrpcVM) GetCpuDelta() uint32 {
	if m != nil {
		return m.CpuDelta
	}
	return 0
}

func init() {
	proto.RegisterType((*GrpcVMConfig)(nil), "cache.GrpcVMConfig")
	proto.RegisterType((*GrpcVM)(nil), "cache.GrpcVM")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CacheService service

type CacheServiceClient interface {
	Config(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*GrpcVMConfig, error)
	GetBaseVM(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*GrpcVM, error)
}

type cacheServiceClient struct {
	cc *grpc.ClientConn
}

func NewCacheServiceClient(cc *grpc.ClientConn) CacheServiceClient {
	return &cacheServiceClient{cc}
}

func (c *cacheServiceClient) Config(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*GrpcVMConfig, error) {
	out := new(GrpcVMConfig)
	err := grpc.Invoke(ctx, "/cache.CacheService/Config", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) GetBaseVM(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*GrpcVM, error) {
	out := new(GrpcVM)
	err := grpc.Invoke(ctx, "/cache.CacheService/GetBaseVM", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CacheService service

type CacheServiceServer interface {
	Config(context.Context, *google_protobuf.Empty) (*GrpcVMConfig, error)
	GetBaseVM(context.Context, *google_protobuf.Empty) (*GrpcVM, error)
}

func RegisterCacheServiceServer(s *grpc.Server, srv CacheServiceServer) {
	s.RegisterService(&_CacheService_serviceDesc, srv)
}

func _CacheService_Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Config(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.CacheService/Config",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Config(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_GetBaseVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).GetBaseVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.CacheService/GetBaseVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).GetBaseVM(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _CacheService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cache.CacheService",
	HandlerType: (*CacheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Config",
			Handler:    _CacheService_Config_Handler,
		},
		{
			MethodName: "GetBaseVM",
			Handler:    _CacheService_GetBaseVM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cache.proto",
}

func init() { proto.RegisterFile("cache.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x14, 0x84, 0x49, 0xd2, 0x46, 0xfb, 0x9a, 0x8a, 0x3c, 0xa1, 0x2c, 0x11, 0x24, 0xf4, 0x94, 0x53,
	0x0a, 0x15, 0x7f, 0x80, 0x36, 0xd2, 0x8b, 0x05, 0x89, 0xd8, 0x7b, 0xba, 0x79, 0x4d, 0x03, 0x4d,
	0x77, 0xd9, 0x6e, 0xc4, 0xfc, 0x31, 0x7f, 0x9f, 0x64, 0x13, 0x43, 0x7b, 0xf0, 0xb6, 0x33, 0xf3,
	0x66, 0x58, 0x3e, 0x18, 0xf3, 0x94, 0xef, 0x29, 0x92, 0x4a, 0x68, 0x81, 0x43, 0x23, 0xfc, 0xfb,
	0x5c, 0x88, 0xfc, 0x40, 0x73, 0x63, 0x6e, 0xab, 0xdd, 0x9c, 0x4a, 0xa9, 0xeb, 0xf6, 0x66, 0x16,
	0x83, 0xb7, 0x52, 0x92, 0x6f, 0xd6, 0x4b, 0x71, 0xdc, 0x15, 0x39, 0x22, 0x0c, 0xe2, 0x54, 0xa7,
	0xcc, 0x0a, 0xac, 0xd0, 0x4b, 0xcc, 0x1b, 0x03, 0x18, 0x3f, 0xe7, 0x74, 0xd4, 0xed, 0x09, 0xb3,
	0x4d, 0x74, 0x6e, 0xcd, 0x7e, 0x2c, 0x70, 0xdb, 0x19, 0xbc, 0x01, 0xbb, 0xc8, 0x4c, 0x7d, 0x94,
	0xd8, 0x45, 0x86, 0x0f, 0x00, 0xfb, 0x5a, 0x92, 0xfa, 0x2a, 0x4e, 0x42, 0x75, 0xdd, 0x33, 0x07,
	0x7d, 0xb8, 0x96, 0x4a, 0x7c, 0xd7, 0xef, 0x45, 0xc6, 0x9c, 0xc0, 0x0a, 0x9d, 0xa4, 0xd7, 0x7d,
	0xf6, 0x99, 0xbc, 0xb1, 0x81, 0x59, 0xec, 0x35, 0xde, 0x82, 0xc3, 0x65, 0xc5, 0x86, 0x81, 0x15,
	0x4e, 0x92, 0xe6, 0x89, 0x53, 0x70, 0x4b, 0x2a, 0x85, 0xaa, 0x99, 0x6b, 0xcc, 0x4e, 0x35, 0x2b,
	0x5c, 0x56, 0x31, 0x1d, 0x74, 0xca, 0xae, 0x4c, 0xd2, 0xeb, 0x45, 0x0d, 0xde, 0xb2, 0x81, 0xf4,
	0xd1, 0x7c, 0x87, 0x13, 0x3e, 0x81, 0xdb, 0x81, 0x98, 0x46, 0x2d, 0xb6, 0xe8, 0x0f, 0x5b, 0xf4,
	0xda, 0x60, 0xf3, 0xef, 0xa2, 0x16, 0xf1, 0x05, 0xb5, 0x05, 0x8c, 0x56, 0xa4, 0x5f, 0xd2, 0x13,
	0x6d, 0xd6, 0xff, 0x36, 0x27, 0x17, 0xcd, 0xad, 0x6b, 0xe2, 0xc7, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xae, 0x34, 0x14, 0x00, 0xb3, 0x01, 0x00, 0x00,
}
